name:                hblas
version:             0.0.0.0
github:              "https://bitbucket.org/mamtajakter/hblas/src/reorganize/#"
license:             BSD3
license-file:        LICENSE
category:            Math
build-type:          Simple
author:              "Mamtaj Akter"
maintainer:          "example@example.com"
copyright:           "Mamtaj Akter"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Haskell Implementation of BLAS

dependencies:
- base
- vector
- time
- criterion
- matrix
- parallel
- random

library:
  extensions: CPP, DeriveDataTypeable
  source-dirs: haskell
  ghc-options: -O2
  exposed-modules:
  - HBLAS.Level1
  - HBLAS.Level2
  - HBLAS.IO.List
  - HBLAS.IO.Vector
  - HBLAS.Class

# executables:
#   northpole:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - hblas

# tests:
#   cg:
#     main:                ConjugateGradient.hs
#     source-dirs:         examples
#     ghc-options:
#     - O2
#     dependencies:
#     - hblas
